{"uuid": "fe195ec1-6373-457f-b6bf-b6bc37acf67d", "children": ["6b4af4d2-5784-4bf4-b9bc-282fe7f660b5", "e881f3d3-ad5d-48f8-add6-3fffb4e404f8", "1b578718-1cb7-4790-b142-6a9e3f8f2e7d", "ceb36908-9233-4d9c-a2d4-9e94f84487c7", "347598ea-5888-4f6b-92e8-1921cc98e2ac", "136ec33c-7ad9-444c-9f11-7b63e7b1644c", "35d8e1d9-2ffc-4592-aaec-d68d8b96fe94", "9061ee2a-ca09-466c-909e-b71bf237b409", "34cc240d-410b-445d-b214-be672483c1a6", "605a384c-8669-4f46-b322-be354eb246dd", "1946881f-7c11-4143-b1c1-d1cb1a5367b0", "9c798446-8cad-45e5-9cdb-be62bc212d8b", "2d9951ef-498b-4454-ac22-4abd7f630bd4", "80597766-ab23-4747-b62a-777356fc96ce", "e15c4377-4135-4030-aca4-9a13a360eb65", "36bb8433-aa2a-464b-acac-1370a8096491", "1da033e8-657b-4b88-9090-41e54a28edb0", "79597c6b-8258-4515-a6d1-6b546bfb93e7", "bb65a46c-7c2f-4f6d-b8c5-29a67a9e7459"], "befores": [{"name": "failed_check", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"failed_check\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/explanation/fixtures.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.\n", "trace": "  File \"/Users/openmindschooling/Library/Python/3.9/lib/python/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/openmindschooling/Library/Python/3.9/lib/python/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/openmindschooling/Library/Python/3.9/lib/python/site-packages/_pytest/fixtures.py\", line 900, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/openmindschooling/MyStuff/Web/Training360/AutomatedTests/Configs/conftest.py\", line 58, in failed_check\n    failed_check()  #Call the screenshot function\n  File \"/Users/openmindschooling/Library/Python/3.9/lib/python/site-packages/_pytest/fixtures.py\", line 1162, in result\n    fail(message, pytrace=False)\n  File \"/Users/openmindschooling/Library/Python/3.9/lib/python/site-packages/_pytest/outcomes.py\", line 196, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1665895810642, "stop": 1665895810642}], "start": 1665895810642, "stop": 1665895812490}