{"uuid": "f74840f1-ab10-4bd3-bd3c-3aca76da3a5d", "children": ["1407b932-1525-47e5-af07-3b1c807da107", "d0ebcbd9-228b-4458-9a46-c9d204388759", "c3b27efd-c484-43c4-bbb3-ca1ef957aa38", "6a2b18de-86ed-4f52-9f13-79809b55bc7e", "3416237e-4775-495c-9f6d-e5b2654c7e29", "0c5042c5-ad79-476f-b94b-741029186bd7", "6015e33e-08c1-4141-ad5b-72a910c083ba", "75b990c5-fde3-4e18-943f-dc8946f968f3", "c842e59a-a447-42a5-8ffd-d9788acf562a", "a92686f9-7894-452c-8ee7-7693fa318ed8", "93b30820-e08b-4d0f-b6d3-c21c360284cf", "003a8923-903b-4fef-8a23-2928c62a9214", "a7df278c-bba4-4457-b15e-d0160914173b", "059bf40a-a7aa-43fa-ba0c-2dfeee8e475e", "5ad24670-9a8f-460d-85dc-e1952a529e79", "1df1e818-c075-4db9-8142-e29a291a5651", "39b0702a-e232-4cca-b65d-e5a749e42c54", "872d9e3b-4f9b-4f67-91ba-e40e6935129c", "2e617b9f-19ee-45cf-a54d-5b0861f25c06"], "befores": [{"name": "failed_check", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"failed_check\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/explanation/fixtures.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.\n", "trace": "  File \"/Users/openmindschooling/Library/Python/3.9/lib/python/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/openmindschooling/Library/Python/3.9/lib/python/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/openmindschooling/Library/Python/3.9/lib/python/site-packages/_pytest/fixtures.py\", line 900, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/openmindschooling/MyStuff/Web/Training360/AutomatedTests/Configs/conftest.py\", line 33, in failed_check\n    failed_check()\n  File \"/Users/openmindschooling/Library/Python/3.9/lib/python/site-packages/_pytest/fixtures.py\", line 1162, in result\n    fail(message, pytrace=False)\n  File \"/Users/openmindschooling/Library/Python/3.9/lib/python/site-packages/_pytest/outcomes.py\", line 196, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1665895548330, "stop": 1665895548330}], "start": 1665895548330, "stop": 1665895549898}