{"content": {"suites": {"0": {"status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_loginpage_title[Chrome]", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_signup_link_visible[Chrome]", "rerun": "0"}, "2": {"status": "FAIL", "message": "   selenium.common.exceptions.TimeoutException: Message:\n       AttributeError: type object 'datetime.datetime' has no attribute 'datetime'\n", "test_name": "test_login[Chrome]", "rerun": "0"}}, "suite_name": "test_login.py"}}}, "date": "February 15, 2022", "start_time": 1644964465.957085, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "2", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "3"}